// Generated by CoffeeScript 1.7.1
(function() {
  var alertObj, data, findCookie, identity, kdactivity, kdlogin, password, serverURL;

  serverURL = "http://test.krashdrive.com";

  identity = "joe+testkd01@megashares.com";

  password = "123456789";

  data = {
    identity: identity,
    password: password,
    remember: 1
  };

  alertObj = function(data) {
    var i;
    for (i in data) {
      alert(i);
    }
  };

  findCookie = function(cookieName) {
    var cookieJar;
    if (document.cookie) {
      return cookieJar = document.cookie.split(';');
    } else {
      return 'no cookie';
    }
  };


  /* -- pointless? local storage is only key/val, iterating and object might create thousands of pairs
  localCookie = (keyName = "kd-localcookiekey", dataObj) ->
  	property for property of dataObj
  		localStorage.setItem cookieName, property
   */

  kdactivity = function() {
    $.ajax({
      type: 'GET',
      url: "" + serverURL + "/joe/activity",
      dataType: 'json'
    }).done(function(response) {
      alert(response.time);
      if (response.error) {
        return alert(response.error_message);
      } else {
        return alert('Woohoo!');
      }
    });
    return $('#files_content').html("response.total");
  };

  kdlogin = function() {
    return $.ajax({
      type: 'POST',
      url: "" + serverURL + "/auth/login",
      data: data,
      dataType: 'json'
    }).done(function(response) {
      if (response.error) {
        return alert(response.error_message);
      } else {
        return alert('Woohoo!' + 'You have successfully authorized KrashDrive Sync.');
      }
    });
  };

  $('#loadDataButton').click(function() {
    return kdlogin();
  });

  $('#loadFilesButton').click(function() {
    return kdactivity();
  });


  /*
                          set_cookie(array(
                              'name'   => 'identity',
                              'value'  => $user->{$this->identity_column},
                              'expire' => $expire
                          ));
  
                          set_cookie(array(
                              'name'   => 'remember_code',
                              'value'  => $salt,
                              'expire' => $expire
                          ));
  
  
  
  
     * Get List of images from server
    getFeed = ->
      $scroller.empty()
      $.ajax(
        url: serverURL + "/images"
        dataType: "json"
        type: "GET"
      ).done (data) ->
        l = data.length
        i = 0
  
        while i < l
          $scroller.append "<img src=\"" + serverURL + "/" + data[i].fileName + "\"/>"
          i++
        return
  
      return
  
    
     * Upload image to server
    upload = (imageURI) ->
      ft = new FileTransfer()
      options = new FileUploadOptions()
      options.fileKey = "file"
      options.fileName = "filename.jpg" # We will use the name auto-generated by Node at the server side.
      options.mimeType = "image/jpeg"
      options.chunkedMode = false
       * Whatever you populate options.params with, will be available in req.body at the server-side.
      options.params = description: "Uploaded from my phone"
      ft.upload imageURI, serverURL + "/images", ((e) ->
        getFeed()
        return
      ), ((e) ->
        alert "Upload failed"
        return
      ), options
      return
  
    
     * Take a picture using the camera or select one from the library
    takePicture = (e) ->
      options =
        quality: 45
        targetWidth: 1000
        targetHeight: 1000
        destinationType: Camera.DestinationType.FILE_URI
        encodingType: Camera.EncodingType.JPEG
        sourceType: Camera.PictureSourceType.CAMERA
  
      navigator.camera.getPicture ((imageURI) ->
        console.log imageURI
        upload imageURI
        return
      ), ((message) ->
      
       * We typically get here because the use canceled the photo operation. Fail silently.
      ), options
      false
  
    $(".camera-btn").on "click", takePicture
    getFeed()
    return
   */

}).call(this);
